name: wizard_app
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #A
  amplify_auth_cognito: ^2.6.3
  amplify_authenticator: ^2.3.5
  amplify_flutter: ^2.6.3
  #B
  #C
  crypto: ^3.0.6
  #F
  flutter_blue_plus: ^1.35.5
  flutter_blue_classic: ^0.0.6
  flutter_image_compress: ^2.4.0
  freezed_annotation: ^3.1.0
  file_picker: ^10.2.4

  #G
  get_it: ^8.0.3
  go_router: ^15.2.4
  #J
  json_annotation: ^4.9.0
  #H
  http: ^1.4.0
  #I
  intl: ^0.20.2
  image_picker: ^1.1.2

  #P
  permission_handler: ^12.0.1
  pdfx: ^2.9.2
  provider: ^6.1.5
  #S
  sqflite: ^2.4.2
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  webview_flutter: ^4.13.0
  cupertino_icons: ^1.0.8

 
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.6.0
  freezed: ^3.2.0
  flutter_lints: ^5.0.0
  json_serializable: ^6.10.0
  test: ^1.25.15




flutter:
  generate: true
 
  uses-material-design: true

  assets:
     - assets/sql/create.sql
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/font/Montserrat-Black.ttf
         - asset: assets/font/Montserrat-BlackItalic.ttf
         - asset: assets/font/Montserrat-Bold.ttf
         - asset: assets/font/Montserrat-BoldItalic.ttf
         - asset: assets/font/Montserrat-ExtraBold.ttf
         - asset: assets/font/Montserrat-ExtraBoldItalic.ttf
         - asset: assets/font/Montserrat-ExtraLight.ttf
         - asset: assets/font/Montserrat-ExtraLightItalic.ttf
         - asset: assets/font/Montserrat-Italic.ttf
         - asset: assets/font/Montserrat-Light.ttf
         - asset: assets/font/Montserrat-LightItalic.ttf
         - asset: assets/font/Montserrat-Medium.ttf
         - asset: assets/font/Montserrat-MediumItalic.ttf
         - asset: assets/font/Montserrat-Regular.ttf
         - asset: assets/font/Montserrat-SemiBold.ttf
         - asset: assets/font/Montserrat-SemiBoldItalic.ttf
         - asset: assets/font/Montserrat-Thin.ttf
         - asset: assets/font/Montserrat-ThinItalic.ttf
           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
